# permissions for end users to view vnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vnet-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - vnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - vnets/status
  verbs:
  - get
