apiVersion: k8s.netris.ai/v1alpha1
kind: VNet
metadata:
  name: netris-operator-test
spec:
  owner: admin
  state: active
  sites:
    - name: yerevan
      switchPorts:
        - name: swp4
          switchName: rlab-leaf1
          vlanId: 1050
        - name: swp5
          switchName: rlab-leaf1
          vlanId: 1050
    - name: san jose
      switchPorts:
        - name: swp10
          switchName: slab-leaf1
          vlanId: 1051
        - name: swp2
          switchName: slab-leaf1
          vlanId: 1051
  gateways:
    - gateway4: 109.23.0.6/24
    - gateway4: 109.25.0.6/24
    - gateway6: 2001:db8:acad::fffe/64
